algoritmo "Calculo de salário"
// Função : calcular salario
// Autor : Thallys
// Data : 12/02/2021
// Seção de Declarações 
var
nome: caractere
diastrabalhado, salario: inteiro
inicio
// Seção de Comandos 
EscrevaL ("Olá, qual o seu nome:")
Leia (nome)
EscrevaL ("Tudo bem,", nome, ". Quantos dias você trabalhou esse mês?")
Leia (diastrabalhado)
salario <- 8*diastrabalhado*25
Escreval (nome, ", seu salário esse mês será:", salario)
fimalgoritmo
