algoritmo "Soma de dois números"
// Função : Somar dois números
// Autor : Thallys
// Data : 21/08/2020
// Seção de Declarações: Aprendendo
var
N1, N2, s, M: real
inicio
// Seção de Comandos 
Escreva ("Escreva um número: ")
leia (N1)
Escreva ("Escreva outro número: ")
Leia (N2)
s <- N1 + N2
M <- (N1 + N2) / 2
Escreval ("O resultado da soma entre ", N1  , " e ", N2, " é: ", s)
Escreva ("E o resultado da média entre eles é: ", M)
fimalgoritmo
